### ISSUE TITLE
Add container image to be able to use the tool with K8s

### ISSUE THREAD

**Issue by berendt** [osism/openstack-image-manager#350]

**Comment by berendt** [comment]
Prepare the setup and published to Pypi: https://github.com/osism/openstack-image-manager/commit/30b51ed4cc361052c90e3bdf39c3767853aea34f

**Comment by kastl-ars** [comment]
Hi @berendt , I was just wondering whether there is a container image for the image manager. Found none, but found this issue. Apparently it was built but was deprecated again?

Because running this "containerized" make make a lot of sense, as openstack and ceph are already running in containers, too. And preparing python virtualenvs is tedious... :-)
