### ISSUE TITLE
hiding of rotated images is not working anymore (since v0.2.3?!)

### ISSUE THREAD

**Issue by maliblatt** [osism/openstack-image-manager#503]
With v0.2.3 the hiding of rotated images seems to be broken. When running the image-manager with the following command:

```
$ tox -- --tag managed_by_our_cloudcompany --hide --cloud admin@dev1
```
it will do the release handling correct, the old image are getting rotated and the new image is correctly named, for example with Debian11:
```
| Debian 11                       | active | public     |
| Debian 11 (20221205-1220)       | active | public     |
```
Output from run:
```
2023-02-28 14:20:55 | INFO     | set_properties:510 - Checking status of 'Debian 11 (20221219-1234)'
2023-02-28 14:20:55 | INFO     | set_properties:519 - Checking visibility of 'Debian 11 (20221219-1234)'
2023-02-28 14:20:55 | INFO     | set_properties:526 - Setting visibility of 'Debian 11 (20221219-1234)' to 'public'
2023-02-28 14:20:56 | INFO     | rename_images:546 - Renaming Debian 11 to Debian 11 (20221205-1220)
2023-02-28 14:20:56 | INFO     | rename_images:550 - Renaming Debian 11 (20221219-1234) to Debian 11
```

But I would expect that the 'Debian 11 (20221205-1220)' should have a visibility of community instead of being public when using the '--hide' parameter.

Before of v0.2.3 the visibility was changed as my expectation.

**Comment by linwalth** [comment]
Indeed we found out that the manager does not start deleting, hiding, or deactivating images beyond the last three, as it is supposed to be hardcoded.

This is not a big matter for us since both Plusserver and Wavecon use the image crawler and thus our image definition files are not supposed to have more than 3 images for our "multi:" images, but it still is either working as intended for our purposes (handing over the responsibility of cutting down image lists to the crawler, essentially) but wrongly documented (https://docs.osism.tech/openstack-image-manager/configuration.html) or it is a bug.

The question is: Is the manager supposed to only keep the latest image and put every other image in the "multi:" image definition file into community visibility - or is it supposed to hold over the last 3 images explicitly?

**It would be very helpful** to have the possibility to set only the latest image to public but to be able to define how many past images we would hold, as it may be confusing for cloud customers to see the latest build as well as the reocurring builds.
